#!/bin/bash -l
#SBATCH --constraint=gpu
#SBATCH --qos=debug
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --gpus=1
#SBATCH --account=m3930
#SBATCH --time=00:05:00
#SBATCH --job-name=job-gpu
#SBATCH --output=log/job-gpu.o%j
#SBATCH --error=log/job-gpu.e%j

# set some openmp variables:
# OMP_PLACES=threads maps OpenMP threads to hardware threads
# OMP_PROC_BIND=spread binds threads as evenly as possible
#
# see https://docs.nersc.gov/jobs/affinity/ for more information

cd build

# nsys
nsys nvprof ./sobel_gpu

# ncu
dcgmi profile --pause
ncu --set default --section SourceCounters --metrics smsp__cycles_active.avg.pct_of_peak_sustained_elapsed,dram__throughput.avg.pct_of_peak_sustained_elapsed,gpu__time_duration.avg ./sobel_gpu

