#!/bin/bash -l
#SBATCH --constraint=cpu
#SBATCH --qos=debug
#SBATCH --nodes=4
#SBATCH --account=m3930
#SBATCH --time=00:15:00
#SBATCH --job-name=job-performance-test
#SBATCH --output=log/job-performance-test.o%j
#SBATCH --error=log/job-performance-test.e%j

cd build
for N in 4 9 16 25 36 49 64 81; do
	echo srun -n $N ./mpi_2dmesh -g 1 -v -o "../data/processed-raw-int8-4x-cpu-row.dat"
	srun -n $N ./mpi_2dmesh -g 1 -v -o "../data/processed-raw-int8-4x-cpu-row.dat"
	echo srun -n $N ./mpi_2dmesh -g 2 -v -o "../data/processed-raw-int8-4x-cpu-col.dat"
	srun -n $N ./mpi_2dmesh -g 2 -v -o "../data/processed-raw-int8-4x-cpu-col.dat"
	echo srun -n $N ./mpi_2dmesh -g 3 -v -o "../data/processed-raw-int8-4x-cpu-tile.dat"
	srun -n $N ./mpi_2dmesh -g 3 -v -o "../data/processed-raw-int8-4x-cpu-tile.dat"
done
