#!/bin/bash -l
#SBATCH --constraint=gpu
#SBATCH --cpus-per-task=1
#SBATCH --qos=debug
#SBATCH --nodes=1
#SBATCH --time=00:15:00
#SBATCH --job-name=job-rt-gpu
#SBATCH --account=m3930
#SBATCH --perf=generic

export OMP_PLACES=threads
export OMP_PROC_BIND=spread

echo ./build/ray-tracing-omp -S 32 -W 512 -D 32 > images/image-gpu.ppm
./build/ray-tracing-omp -S 32 -W 512 -D 32 > images/image-gpu.ppm
