#!/bin/bash -l
#SBATCH --constraint=cpu
#SBATCH --qos=debug
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --account=m3930
#SBATCH --time=00:05:00
#SBATCH --job-name=job-cpu
#SBATCH --output=log/job-cpu.o%j
#SBATCH --error=log/job-cpu.e%j

# set some openmp variables:
# OMP_PLACES=threads maps OpenMP threads to hardware threads
# OMP_PROC_BIND=spread binds threads as evenly as possible
#
# see https://docs.nersc.gov/jobs/affinity/ for more information

unset OMP_NUM_THREADS
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

cd build

for t in 1 2 4 8 16; do # loop over concurrency level
	echo OMP_NUM_THREADS=$t ./sobel_cpu
	OMP_NUM_THREADS=$t ./sobel_cpu
done
