#!/bin/bash -l
#SBATCH --constraint=cpu
#SBATCH --cpus-per-task=1
#SBATCH --qos=debug
#SBATCH --nodes=1
#SBATCH --time=00:30:00
#SBATCH --job-name=job-rt
#SBATCH --account=m3930
#SBATCH --perf=generic
#SBATCH --output=log/%j-job-rt.out

export OMP_PLACES=threads
export OMP_PROC_BIND=spread
unset OMP_NUM_THREADS

export PERF_COUNTER_GROUP=FLOPS_DP
export MARKER_FLAG="-m"

#for t in 256 128 64 32 16 8 4 2 1; do
for t in 256 128 64 32; do
	let maxcore=$t-1
	echo likwid-perfctr -m $MARKER_FLAG $PERF_COUNTER_GROUP -C N:0-$maxcore ./ray-tracing-omp -S 32 -W 512 -H 288 -D 32 -o images/image-$t.ppm
	likwid-perfctr -m $MARKER_FLAG $PERF_COUNTER_GROUP -C N:0-$maxcore ./ray-tracing-omp -S 32 -W 512 -H 288 -D 32 -o images/image-$t.ppm
done

for t in 256 128 64 32; do
	let maxcore=$t-1
	echo likwid-perfctr -m $MARKER_FLAG $PERF_COUNTER_GROUP -C N:0-$maxcore ./ray-tracing-omp_collapse -S 32 -W 512 -H 288 -D 32 -o images/image-collapse-$t.ppm
	likwid-perfctr -m $MARKER_FLAG $PERF_COUNTER_GROUP -C N:0-$maxcore ./ray-tracing-omp_collapse -S 32 -W 512 -H 288 -D 32 -o images/image-collapse-$t.ppm
done

