#!/bin/bash -l
#SBATCH --constraint=gpu
#SBATCH --qos=debug
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --gpus=1
#SBATCH --account=m3930
#SBATCH --time=00:30:00
#SBATCH --job-name=job-gpu
#SBATCH --output=log/job-gpu.o%j
#SBATCH --error=log/job-gpu.e%j

cd build

# nsys
# nsys nvprof ./sobel_gpu

# ncu
dcgmi profile --pause

for T in 32 64 128 256 512 1024; do # Iterate over the number of `Threads per block`
   for B in 1 4 16 64 256 1024 4096; do  # Iterate over the number of `Thread Blocks`
      echo ncu --set default --section SourceCounters --metrics smsp__cycles_active.avg.pct_of_peak_sustained_elapsed,dram__throughput.avg.pct_of_peak_sustained_elapsed,gpu__time_duration.avg ./sobel_gpu -T $T -B $B
      ncu --set default --section SourceCounters --metrics smsp__cycles_active.avg.pct_of_peak_sustained_elapsed,dram__throughput.avg.pct_of_peak_sustained_elapsed,gpu__time_duration.avg ./sobel_gpu -T $T -B $B
   done
done
