#!/bin/bash -l
#SBATCH --constraint=cpu
#SBATCH --cpus-per-task=1
#SBATCH --qos=debug
#SBATCH --nodes=1
#SBATCH --time=00:30:00
#SBATCH --job-name=job-rt
#SBATCH --account=m3930
#SBATCH --perf=generic
#SBATCH --output=log/%j-job-rt.out
#SBATCH --error=log/%j-job-rt.out

export OMP_PLACES=threads
export OMP_PROC_BIND=spread
unset OMP_NUM_THREADS

export PERF_COUNTER_GROUP=FLOPS_DP
export MARKER_FLAG="-m"

#for t in 256 128 64 32 16 8 4 2 1; do
for schedule in static dynamic; do
	echo "Experiments with $schedule without collapse"
	for t in 256 128 64 32; do
		echo OMP_SCHEDULE=$schedule OMP_NUM_THREADS=$t ./build/ray-tracing-omp -S 32 -W 512 -H 288 -D 32 -o images/image-$t.ppm
		OMP_SCHEDULE=$schedule OMP_NUM_THREADS=$t ./build/ray-tracing-omp -S 32 -W 512 -H 288 -D 32 -o images/image-$t.ppm
	done

	echo "Experiments with $schedule with collapse"
	for t in 256 128 64 32; do
		echo OMP_SCHEDULE=$schedule OMP_NUM_THREADS=$t ./build/ray-tracing-omp_collapse -S 32 -W 512 -H 288 -D 32 -o images/image-collapse-$t.ppm
		OMP_SCHEDULE=$schedule OMP_NUM_THREADS=$t ./build/ray-tracing-omp_collapse -S 32 -W 512 -H 288 -D 32 -o images/image-collapse-$t.ppm
	done
done

