#!/bin/bash -l
#SBATCH --constraint=cpu
#SBATCH --cpus-per-task=1
#SBATCH --qos=debug
#SBATCH --nodes=1
#SBATCH --time=00:30:00
#SBATCH --job-name=job-rt
#SBATCH --account=m3930
#SBATCH --perf=generic
#SBATCH --output=log/%j-job-rt.out
#SBATCH --error=log/%j-job-rt.out

export OMP_PLACES=threads
export OMP_PROC_BIND=spread
unset OMP_NUM_THREADS

concurrency_levels=(1 2 4 8 16 32 64 128 256)

for t in ${concurrency_levels[@]}; do
	let samples=32*$t
	echo OMP_SCHEDULE=static OMP_NUM_THREADS=$t ../build/ray-tracing-omp -S $samples -W 512 -H 288 -D 32 -o images/static-image-$t.ppm
	OMP_SCHEDULE=static OMP_NUM_THREADS=$t ../build/ray-tracing-omp -S $samples -W 512 -H 288 -D 32 -o images/static-image-$t.ppm
done
